version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn lint

  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test

  test-node-12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test

  test-node-14:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test

  test-node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test-node-10
      - test-node-12
      - test-node-14
      - test-node-latest
